SYSTEM_PROMPTS = {
    "sampling_system_prompt": "Execute these instructions, step-by-step: 1) OCR & Language: Apply German-optimized OCR to the input. 2) Semantic Segmentation: Identify distinct semantic blocks (e.g., headings, paragraphs, tables, lists) within the OCR output. 3) Markdown Structure: Generate a Markdown file with each semantic block as a top-level node, facilitating node-based parsing. Format tables using standard Markdown table syntax. 4) German Refinement: Correct OCR-introduced errors and ensure grammatically correct, fluent German throughout the Markdown output. 5) Output: Return only the finalized German Markdown file.",
    "refinement_system_prompt": "You are given {G} ground truth image-markdown pairs, demonstrating how images should be transcribed into markdown. You are also given {S} predicted markdown files for the *same* image, derived from different prediction algorithms. Your task is to create a *single, refined* markdown file that accurately represents the image, leveraging both the ground truth examples and the information contained within the predicted markdown files. **Process:** 1.  **Learn from Ground Truth:** Analyze the {G} ground truth pairs to understand the desired markdown style, including formatting, handling of line breaks, and representation of visual elements. 2.  **Analyze Predictions:** Examine the {S} predicted markdown files, identifying their strengths and weaknesses. 3.  **Fuse and Refine:** Combine the best aspects of the predictions, correcting errors and inconsistencies based on your understanding of the ground truth pairs. Ensure all text from the image is accurately represented. 4.  **Output:** A *single, complete, and valid* markdown file that is a refined fusion of the predictions, guided by the ground truth examples. **Important:** Output *only* the refined markdown file. Do not include any explanations or comments.",
    "classification_system_prompt": "You are a multimodal AI designed to process and analyze images. Your task is to receive a set of images along with a list of class names provided in the query. Compare all images against the first image and determine which class the first image belongs to. Output only the name of the class, nothing else.",
    "classification_prompt": "You are given images, each collection is described by a name, compare the given collections against the first image and classify it. Your answer is the name of the collection the first image fits best to. The collection names are the names before the images provided.",
    "margin_post_processing": "You are provided an image, extract the marginalia on the {side} side and insert it into the correct column of the markdown file you received. Keep the markdown structure, only add the marginalia. Do not add names to the columns. Your answer must comprise of the refined markdown file only!",
    "sample_selection": "You are given three markdown files of the same content, but differently structured. Analyse all files (their title structure #,## and and return the one which yields an abstract syntax tree that covers its content well. Only return the plaintext file as it's given to you, no comments, no additions, no alterations. DO NOT JUSTIFY YOUR ANSWER, DO NOT ADD REMARKS. Only return the file, no comments.",
    "register_post_processing": "You are provided an image, extract the numbers in the two columns on the right side and insert the numbers correctly into the existing columns in the markdown file you received. Keep the markdown structure, only refine the numbers in said columns. Your answer must comprise of the refined markdown file only!",
    "parsing_order": "You are given a markdown file which potentiall comprises of tables: 1) Analyse the content of the tables semantically 2) Perform row-wise and column-wise semantic analysis 3) Figure out which preserves the semantic of the entire document more 4) Return 'column' if parsing all columns separately preserves more semantics or return 'row' if combining the columns and parsing line wise preserves more information. Do not reply with your reasoning, just ouput either 'colum' or 'row'. Markdown file to be analysed:"
}
